spring:
  output.ansi.enabled: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  data:
    web:
      pageable: # pageable default global config
        default-page-size: 10
        max-page-size: 2000
#        one-indexed-parameters: true # start page index 1 (not recommend - because not accurate pageable info)

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace